#主题设置
#-----------------------------基础设置------------------------------------------
avatar: /image/avatar.png  #头像
description: 知晓天空之蓝的人啊 #介绍
name: 小三玖のblog #名字
#-----------------------------导航栏设置------------------------------------------
#用法: 延续下列格式(添加新页面需要手动创建新页面)
menus: 
  首页: /
  归档: /archives
  朋友: /friend
  关于: /about
#-----------------------------友链自定义------------------------------------------
friend:
  -
    name: MixJiaのblog
    link: https://blog.mixjia233.com/
    img: http://q1.qlogo.cn/g?b=qq&nk=2096002533&s=100
  -
    name: company3
    link: https://www.google.com.hk/
    img: /img/2.jpg
  -
    name: company4
    link: https://www.google.com.hk/
    img: /img/1.jpg
  -
    name: company4
    link: https://www.google.com.hk/
    img: /img/1.jpg
  -
    name: company4
    link: https://www.google.com.hk/
    img: /img/1.jpg
#-----------------------------主题样式自定义------------------------------------------
theme-border-radius: '6px'

#------------------------------页脚设置-----------------------------------------------
copyright: © 2022 dalaoshi777
 